#!/usr/bin/env python3
"""WasmGC sandbox-boundary corpus generator.

Generates JS test cases that exercise V8 Wasm operations near the sandbox
boundary: table lazy resolution, func ref creation, GC struct/array type
casting, cross-instance references, dispatch table indexing.

Designed to run under: d8 --sandbox-fuzzing <generated>.js
The sandbox crash filter detects if any operation escapes the sandbox.

Usage:
  python3 gen_wasm_sandbox_boundary_corpus.py --out-dir ./corpus --count 200
  python3 gen_wasm_sandbox_boundary_corpus.py --out-dir ./corpus --count 50 --surface table_lazy
"""
import argparse
import random
import sys
from pathlib import Path

SURFACES = [
    "table_lazy",
    "table_cross_instance",
    "funcref_resolution",
    "gc_struct_cast",
    "gc_array_bounds",
    "multi_table_dispatch",
    "table_grow_funcref",
    "gc_subtype_hierarchy",
    "import_reexport_chain",
    "memory_boundary",
]


def header(seed: int) -> str:
    return f"""\
// Generated by gen_wasm_sandbox_boundary_corpus.py seed={seed}
// Run: d8 --sandbox-fuzzing <this file>
d8.file.execute('test/mjsunit/wasm/wasm-module-builder.js');

function tryRun(fn, label) {{
  try {{ fn(); }} catch (e) {{
    // Swallow expected traps/errors — sandbox violations are caught by the filter
  }}
}}
"""


def gen_table_lazy(seed: int) -> str:
    rng = random.Random(seed)
    num_funcs = rng.randint(3, 16)
    table_size = rng.randint(num_funcs, num_funcs + 20)
    num_reads = rng.randint(5, 30)
    read_calls = "\n".join(
        f'  tryRun(() => instance.exports.call_via_table('
        f'{rng.randint(0, table_size - 1)}, {rng.randint(0, 100)}), "call_indirect_{i}");'
        for i in range(num_reads)
    )
    return header(seed) + f"""
// Surface: table_lazy — lazy Tuple2(instance, func_index) resolution via table.get
(function() {{
  const builder = new WasmModuleBuilder();
  const sig = builder.addType(kSig_i_i);

  for (let i = 0; i < {num_funcs}; i++) {{
    builder.addFunction('f' + i, kSig_i_i)
      .addBody([kExprLocalGet, 0, kExprI32Const, i + 1, kExprI32Add])
      .exportFunc();
  }}

  const table = builder.addTable(kWasmFuncRef, {table_size}, {table_size});
  builder.addActiveElementSegment(table.index, wasmI32Const(0),
    {list(range(num_funcs))});
  builder.addExportOfKind('tbl', kExternalTable, table.index);

  builder.addFunction('call_via_table', makeSig([kWasmI32, kWasmI32], [kWasmI32]))
    .addBody([
      kExprLocalGet, 1,
      kExprLocalGet, 0,
      kExprCallIndirect, sig, table.index,
    ])
    .exportFunc();

  const instance = builder.instantiate();

  for (let i = 0; i < {table_size}; i++) {{
    tryRun(() => instance.exports.tbl.get(i), 'tbl.get(' + i + ')');
  }}

{read_calls}

  tryRun(() => {{
    instance.exports.tbl.grow({rng.randint(1, 10)});
    for (let i = {table_size}; i < instance.exports.tbl.length; i++) {{
      let ref = instance.exports.tbl.get(i);
    }}
  }}, 'grow_and_read');
}})();
"""


def gen_table_cross_instance(seed: int) -> str:
    rng = random.Random(seed)
    num_funcs_a = rng.randint(2, 8)
    num_funcs_b = rng.randint(2, 8)
    table_size = max(num_funcs_a, num_funcs_b) + rng.randint(2, 10)
    return header(seed) + f"""
// Surface: table_cross_instance — cross-instance funcref via shared table
(function() {{
  const builderA = new WasmModuleBuilder();
  for (let i = 0; i < {num_funcs_a}; i++) {{
    builderA.addFunction('fa' + i, kSig_i_i)
      .addBody([kExprLocalGet, 0, kExprI32Const, 10 + i, kExprI32Mul])
      .exportFunc();
  }}
  const instanceA = builderA.instantiate();

  const builderB = new WasmModuleBuilder();
  const table = builderB.addTable(kWasmFuncRef, {table_size}, {table_size});
  builderB.addExportOfKind('tbl', kExternalTable, table.index);
  for (let i = 0; i < {num_funcs_b}; i++) {{
    builderB.addFunction('fb' + i, kSig_i_i)
      .addBody([kExprLocalGet, 0, kExprI32Const, 20 + i, kExprI32Add])
      .exportFunc();
  }}
  const sig = builderB.addType(kSig_i_i);
  builderB.addFunction('call_table', makeSig([kWasmI32, kWasmI32], [kWasmI32]))
    .addBody([kExprLocalGet, 1, kExprLocalGet, 0, kExprCallIndirect, sig, table.index])
    .exportFunc();
  const instanceB = builderB.instantiate();

  for (let i = 0; i < {num_funcs_a}; i++) {{
    tryRun(() => instanceB.exports.tbl.set(i, instanceA.exports['fa' + i]), 'cross_set_' + i);
  }}
  for (let i = 0; i < {num_funcs_b}; i++) {{
    tryRun(() => instanceB.exports.tbl.set({num_funcs_a} + i, instanceB.exports['fb' + i]), 'self_set_' + i);
  }}

  for (let idx = 0; idx < {num_funcs_a + num_funcs_b}; idx++) {{
    tryRun(() => instanceB.exports.call_table(idx, idx * 3), 'call_' + idx);
  }}

  for (let i = 0; i < instanceB.exports.tbl.length; i++) {{
    tryRun(() => {{ let ref = instanceB.exports.tbl.get(i); }}, 'read_' + i);
  }}
}})();
"""


def gen_funcref_resolution(seed: int) -> str:
    rng = random.Random(seed)
    num_funcs = rng.randint(10, 64)
    table_size = num_funcs + rng.randint(0, 16)
    num_instances = rng.randint(2, 5)
    cross_count = min(num_funcs, 8)
    return header(seed) + f"""
// Surface: funcref_resolution — stress GetOrCreateFuncRef with many functions
(function() {{
  const builder = new WasmModuleBuilder();
  const sig = builder.addType(kSig_i_i);

  for (let i = 0; i < {num_funcs}; i++) {{
    builder.addFunction('f' + i, kSig_i_i)
      .addBody([kExprLocalGet, 0, kExprI32Const, i, kExprI32Xor])
      .exportFunc();
  }}

  const table = builder.addTable(kWasmFuncRef, {table_size}, {table_size});
  builder.addActiveElementSegment(table.index, wasmI32Const(0),
    {list(range(num_funcs))});
  builder.addExportOfKind('tbl', kExternalTable, table.index);

  builder.addFunction('call_tbl', makeSig([kWasmI32, kWasmI32], [kWasmI32]))
    .addBody([kExprLocalGet, 1, kExprLocalGet, 0, kExprCallIndirect, sig, table.index])
    .exportFunc();

  const instances = [];
  for (let n = 0; n < {num_instances}; n++) {{
    tryRun(() => instances.push(builder.instantiate()), 'instantiate_' + n);
  }}

  for (const inst of instances) {{
    for (let i = 0; i < {table_size}; i++) {{
      tryRun(() => inst.exports.tbl.get(i), 'get');
    }}
  }}

  if (instances.length >= 2) {{
    for (let i = 0; i < {cross_count}; i++) {{
      tryRun(() => {{
        let ref = instances[0].exports.tbl.get(i);
        instances[1].exports.tbl.set(i, ref);
      }}, 'cross_write_' + i);
    }}
    for (let i = 0; i < {cross_count}; i++) {{
      tryRun(() => instances[1].exports.call_tbl(i, 42), 'cross_call_' + i);
    }}
  }}
}})();
"""


def gen_gc_struct_cast(seed: int) -> str:
    rng = random.Random(seed)
    depth = rng.randint(2, 5)
    num_casts = rng.randint(5, 20)
    cast_calls = "\n".join(
        f'  tryRun(() => instance.exports.create_and_cast({rng.randint(0, 1000)}), "cast_{i}");'
        for i in range(num_casts)
    )
    sub_calls = "\n".join(
        f'  tryRun(() => instance.exports.create_sub_read_base({rng.randint(0, 1000)}), "sub_read_{i}");'
        for i in range(num_casts)
    )
    return header(seed) + f"""
// Surface: gc_struct_cast — WasmGC subtype hierarchy with ref.cast/ref.test
(function() {{
  const builder = new WasmModuleBuilder();

  // Base: 2 i32 fields
  const base = builder.addStruct([makeField(kWasmI32, true), makeField(kWasmI32, true)]);
  // Sub chain: each extends previous, adds one more i32 field
  const types = [base];
  for (let i = 1; i < {depth}; i++) {{
    const fields = [];
    for (let f = 0; f < 2 + i; f++) fields.push(makeField(kWasmI32, true));
    types.push(builder.addStruct(fields, {{supertype: types[i - 1]}}));
  }}

  // Create base, test if it's the deepest subtype (should be false)
  builder.addFunction('create_and_cast', kSig_i_i)
    .addLocals(wasmRefNullType(types[0]), 1)
    .addBody([
      kExprLocalGet, 0,
      kExprI32Const, 77,
      kGCPrefix, kExprStructNew, types[0],
      kExprLocalSet, 1,
      kExprLocalGet, 1,
      kGCPrefix, kExprRefTest, types[{depth - 1}],
    ])
    .exportFunc();

  // Create deepest subtype, read field 0 via base type view
  builder.addFunction('create_sub_read_base', kSig_i_i)
    .addLocals(wasmRefNullType(types[{depth - 1}]), 1)
    .addBody([
      // Push 2 + (depth-1) i32 args for deepest struct
      ...Array.from({{length: {depth + 1}}}, (_, i) => [kExprI32Const, i + 1]).flat(),
      kGCPrefix, kExprStructNew, types[{depth - 1}],
      kExprLocalSet, 1,
      kExprLocalGet, 1,
      kGCPrefix, kExprStructGet, types[{depth - 1}], 0,
    ])
    .exportFunc();

  const instance = builder.instantiate();

{cast_calls}
{sub_calls}
}})();
"""


def gen_gc_array_bounds(seed: int) -> str:
    rng = random.Random(seed)
    init_len = rng.randint(4, 64)
    num_ops = rng.randint(10, 30)
    ops_calls = "\n".join(
        f'  tryRun(() => instance.exports.array_ops({rng.randint(0, 255)}, {rng.randint(1, init_len)}), "ops_{i}");'
        for i in range(num_ops)
    )
    read_calls = "\n".join(
        f'  tryRun(() => instance.exports.array_read(0, {init_len}, {rng.randint(0, init_len + 5)}), "read_{i}");'
        for i in range(num_ops // 2)
    )
    wr_calls = "\n".join(
        f'  tryRun(() => instance.exports.array_write_read({rng.randint(0, 0xffff)}, {init_len}, {rng.randint(0, init_len - 1)}), "wr_{i}");'
        for i in range(num_ops // 2)
    )
    return header(seed) + f"""
// Surface: gc_array_bounds — WasmGC array create/get/set/len near boundaries
(function() {{
  const builder = new WasmModuleBuilder();
  const arrayType = builder.addArray(kWasmI32);

  builder.addFunction('array_ops', makeSig([kWasmI32, kWasmI32], [kWasmI32]))
    .addLocals(wasmRefNullType(arrayType), 1)
    .addBody([
      kExprLocalGet, 0,
      kExprLocalGet, 1,
      kGCPrefix, kExprArrayNew, arrayType,
      kExprLocalSet, 2,
      kExprLocalGet, 2,
      kGCPrefix, kExprArrayLen,
    ])
    .exportFunc();

  builder.addFunction('array_read', makeSig([kWasmI32, kWasmI32, kWasmI32], [kWasmI32]))
    .addLocals(wasmRefNullType(arrayType), 1)
    .addBody([
      kExprLocalGet, 0,
      kExprLocalGet, 1,
      kGCPrefix, kExprArrayNew, arrayType,
      kExprLocalSet, 3,
      kExprLocalGet, 3,
      kExprLocalGet, 2,
      kGCPrefix, kExprArrayGet, arrayType,
    ])
    .exportFunc();

  builder.addFunction('array_write_read', makeSig([kWasmI32, kWasmI32, kWasmI32], [kWasmI32]))
    .addLocals(wasmRefNullType(arrayType), 1)
    .addBody([
      kExprI32Const, 0,
      kExprLocalGet, 1,
      kGCPrefix, kExprArrayNew, arrayType,
      kExprLocalSet, 3,
      kExprLocalGet, 3,
      kExprLocalGet, 2,
      kExprLocalGet, 0,
      kGCPrefix, kExprArraySet, arrayType,
      kExprLocalGet, 3,
      kExprLocalGet, 2,
      kGCPrefix, kExprArrayGet, arrayType,
    ])
    .exportFunc();

  const instance = builder.instantiate();

{ops_calls}
{read_calls}
{wr_calls}
}})();
"""


def gen_multi_table_dispatch(seed: int) -> str:
    rng = random.Random(seed)
    num_tables = rng.randint(2, 4)
    funcs_per_table = rng.randint(3, 10)
    swap_count = min(funcs_per_table, 5)
    return header(seed) + f"""
// Surface: multi_table_dispatch — multiple tables, mixed sigs, call_indirect
(function() {{
  const builder = new WasmModuleBuilder();
  const sig_ii = builder.addType(kSig_i_i);
  const sig_iii = builder.addType(kSig_i_ii);
  const sig_v = builder.addType(kSig_v_v);

  const tables = [];
  for (let t = 0; t < {num_tables}; t++) {{
    tables.push(builder.addTable(kWasmFuncRef, {funcs_per_table + 4}, {funcs_per_table + 4}));
  }}

  const funcIndices = [];
  for (let i = 0; i < {funcs_per_table}; i++) {{
    funcIndices.push(builder.addFunction('fi_' + i, kSig_i_i)
      .addBody([kExprLocalGet, 0, kExprI32Const, i, kExprI32Add]).index);
  }}
  for (let i = 0; i < {funcs_per_table}; i++) {{
    funcIndices.push(builder.addFunction('fii_' + i, kSig_i_ii)
      .addBody([kExprLocalGet, 0, kExprLocalGet, 1, kExprI32Mul]).index);
  }}

  for (let t = 0; t < {num_tables}; t++) {{
    const elems = [];
    for (let i = 0; i < {funcs_per_table}; i++) {{
      elems.push(funcIndices[(t * 3 + i) % funcIndices.length]);
    }}
    builder.addActiveElementSegment(tables[t].index, wasmI32Const(0), elems);
  }}

  for (let t = 0; t < {num_tables}; t++) {{
    builder.addExportOfKind('t' + t, kExternalTable, tables[t].index);
  }}

  for (let t = 0; t < {num_tables}; t++) {{
    builder.addFunction('call_t' + t, makeSig([kWasmI32, kWasmI32], [kWasmI32]))
      .addBody([kExprLocalGet, 1, kExprLocalGet, 0, kExprCallIndirect, sig_ii, tables[t].index])
      .exportFunc();
  }}

  const instance = builder.instantiate();

  for (let t = 0; t < {num_tables}; t++) {{
    for (let i = 0; i < {funcs_per_table}; i++) {{
      tryRun(() => instance.exports['call_t' + t](i, 7), 'call_t' + t + '_' + i);
    }}
  }}

  for (let i = 0; i < {swap_count}; i++) {{
    tryRun(() => {{
      let ref0 = instance.exports.t0.get(i);
      let ref1 = instance.exports.t1.get(i);
      instance.exports.t0.set(i, ref1);
      instance.exports.t1.set(i, ref0);
    }}, 'swap_' + i);
  }}

  for (let t = 0; t < {num_tables}; t++) {{
    for (let i = 0; i < {funcs_per_table}; i++) {{
      tryRun(() => instance.exports['call_t' + t](i, 13), 'recall_t' + t + '_' + i);
    }}
  }}
}})();
"""


def gen_table_grow_funcref(seed: int) -> str:
    rng = random.Random(seed)
    initial = rng.randint(2, 8)
    grow_steps = rng.randint(3, 10)
    grow_by = rng.randint(1, 20)
    return header(seed) + f"""
// Surface: table_grow_funcref — grow reallocates dispatch table, then set/get/call
(function() {{
  const builder = new WasmModuleBuilder();
  const sig = builder.addType(kSig_i_i);

  for (let i = 0; i < {initial}; i++) {{
    builder.addFunction('f' + i, kSig_i_i)
      .addBody([kExprLocalGet, 0, kExprI32Const, i * 7, kExprI32Add])
      .exportFunc();
  }}

  const table = builder.addTable(kWasmFuncRef, {initial});
  builder.addActiveElementSegment(table.index, wasmI32Const(0),
    {list(range(initial))});
  builder.addExportOfKind('tbl', kExternalTable, table.index);

  builder.addFunction('call_tbl', makeSig([kWasmI32, kWasmI32], [kWasmI32]))
    .addBody([kExprLocalGet, 1, kExprLocalGet, 0, kExprCallIndirect, sig, table.index])
    .exportFunc();

  const instance = builder.instantiate();

  // Grow via JS API (avoids ref.null encoding in Wasm body)
  for (let step = 0; step < {grow_steps}; step++) {{
    tryRun(() => {{
      let oldSize = instance.exports.tbl.length;
      instance.exports.tbl.grow({grow_by});
      instance.exports.tbl.set(oldSize, instance.exports.f0);
      instance.exports.call_tbl(oldSize, 99);
    }}, 'grow_step_' + step);

    tryRun(() => {{
      for (let i = 0; i < instance.exports.tbl.length; i++) {{
        instance.exports.tbl.get(i);
      }}
    }}, 'read_all_' + step);
  }}
}})();
"""


def gen_gc_subtype_hierarchy(seed: int) -> str:
    rng = random.Random(seed)
    depth = rng.randint(3, 7)
    num_fields_base = rng.randint(2, 4)
    total_fields_deep = num_fields_base + depth - 1
    total_fields_mid = num_fields_base + depth // 2
    return header(seed) + f"""
// Surface: gc_subtype_hierarchy — deep hierarchy, ref.cast at every level
(function() {{
  const builder = new WasmModuleBuilder();
  const types = [];

  const baseFields = [];
  for (let f = 0; f < {num_fields_base}; f++) {{
    baseFields.push(makeField(kWasmI32, true));
  }}
  types.push(builder.addStruct(baseFields));

  for (let d = 1; d < {depth}; d++) {{
    const fields = [...baseFields];
    for (let extra = 0; extra < d; extra++) {{
      fields.push(makeField(kWasmI32, true));
    }}
    types.push(builder.addStruct(fields, {{supertype: types[d - 1]}}));
  }}

  // Create deepest subtype, cast down from eqref
  builder.addFunction('deep_cast', makeSig([kWasmI32], [kWasmI32]))
    .addLocals(kWasmEqRef, 1)
    .addBody([
      ...Array({total_fields_deep}).fill(0).flatMap((_, i) => [kExprI32Const, i + 1]),
      kGCPrefix, kExprStructNew, types[{depth - 1}],
      kExprLocalSet, 1,
      kExprLocalGet, 1,
      kGCPrefix, kExprRefCast, types[{depth - 1}],
      kGCPrefix, kExprStructGet, types[{depth - 1}], 0,
    ])
    .exportFunc();

  // Create mid-level type, test if it's deepest (should be false)
  builder.addFunction('mid_cast_fail', makeSig([kWasmI32], [kWasmI32]))
    .addLocals(kWasmEqRef, 1)
    .addBody([
      ...Array({total_fields_mid}).fill(0).flatMap((_, i) => [kExprI32Const, i + 10]),
      kGCPrefix, kExprStructNew, types[{depth // 2}],
      kExprLocalSet, 1,
      kExprLocalGet, 1,
      kGCPrefix, kExprRefTest, types[{depth - 1}],
    ])
    .exportFunc();

  const table = builder.addTable(kWasmAnyRef, {depth + 2});
  builder.addExportOfKind('tbl', kExternalTable, table.index);

  builder.addFunction('store_in_table', makeSig([kWasmI32], []))
    .addBody([
      kExprLocalGet, 0,
      ...Array({num_fields_base}).fill(0).flatMap((_, i) => [kExprI32Const, i]),
      kGCPrefix, kExprStructNew, types[0],
      kExprTableSet, table.index,
    ])
    .exportFunc();

  const instance = builder.instantiate();

  for (let i = 0; i < {depth * 3}; i++) {{
    tryRun(() => instance.exports.deep_cast(i), 'deep_' + i);
    tryRun(() => instance.exports.mid_cast_fail(i), 'mid_' + i);
  }}

  for (let i = 0; i < {depth}; i++) {{
    tryRun(() => {{
      instance.exports.store_in_table(i);
      instance.exports.tbl.get(i);
    }}, 'table_store_' + i);
  }}
}})();
"""


def gen_import_reexport_chain(seed: int) -> str:
    rng = random.Random(seed)
    chain_len = rng.randint(2, 5)
    return header(seed) + f"""
// Surface: import_reexport_chain — funcrefs pass through import/re-export chain
(function() {{
  let prevExports = null;

  for (let c = 0; c < {chain_len}; c++) {{
    const builder = new WasmModuleBuilder();

    if (prevExports) {{
      const imp = builder.addImport('prev', 'f', kSig_i_i);
      const table = builder.addTable(kWasmFuncRef, 4, 4);
      builder.addActiveElementSegment(table.index, wasmI32Const(0), [imp]);
      builder.addExportOfKind('tbl', kExternalTable, table.index);
      builder.addFunction('f', kSig_i_i)
        .addBody([kExprLocalGet, 0, kExprI32Const, c, kExprI32Add,
                  kExprCallFunction, imp])
        .exportFunc();
    }} else {{
      builder.addFunction('f', kSig_i_i)
        .addBody([kExprLocalGet, 0, kExprI32Const, 1, kExprI32Add])
        .exportFunc();
      const table = builder.addTable(kWasmFuncRef, 4, 4);
      builder.addActiveElementSegment(table.index, wasmI32Const(0), [0]);
      builder.addExportOfKind('tbl', kExternalTable, table.index);
    }}

    const imports = prevExports ? {{prev: {{f: prevExports.f}}}} : {{}};
    tryRun(() => {{
      const instance = builder.instantiate(imports);
      prevExports = instance.exports;
    }}, 'chain_' + c);
  }}

  if (prevExports) {{
    for (let i = 0; i < 10; i++) {{
      tryRun(() => prevExports.f(i), 'chain_call_' + i);
    }}
    tryRun(() => {{
      for (let i = 0; i < prevExports.tbl.length; i++) {{
        prevExports.tbl.get(i);
      }}
    }}, 'chain_table_read');
  }}
}})();
"""


def gen_memory_boundary(seed: int) -> str:
    rng = random.Random(seed)
    init_pages = rng.randint(1, 4)
    max_pages = init_pages + rng.randint(2, 10)
    return header(seed) + f"""
// Surface: memory_boundary — memory.grow + boundary access interleave
(function() {{
  const builder = new WasmModuleBuilder();
  builder.addMemory({init_pages}, {max_pages});
  builder.exportMemoryAs('mem');

  builder.addFunction('store32', makeSig([kWasmI32, kWasmI32], []))
    .addBody([kExprLocalGet, 0, kExprLocalGet, 1, kExprI32StoreMem, 2, 0])
    .exportFunc();

  builder.addFunction('load32', makeSig([kWasmI32], [kWasmI32]))
    .addBody([kExprLocalGet, 0, kExprI32LoadMem, 2, 0])
    .exportFunc();

  builder.addFunction('grow', makeSig([kWasmI32], [kWasmI32]))
    .addBody([kExprLocalGet, 0, kExprMemoryGrow, 0])
    .exportFunc();

  builder.addFunction('fill', makeSig([kWasmI32, kWasmI32, kWasmI32], []))
    .addBody([kExprLocalGet, 0, kExprLocalGet, 1, kExprLocalGet, 2,
              kNumericPrefix, kExprMemoryFill, 0])
    .exportFunc();

  const instance = builder.instantiate();

  const pageSize = 65536;
  let currentPages = {init_pages};

  for (let off = -8; off <= 0; off += 4) {{
    let addr = currentPages * pageSize + off;
    if (addr >= 0) {{
      tryRun(() => {{
        instance.exports.store32(addr, 0xDEADBEEF);
        instance.exports.load32(addr);
      }}, 'boundary_' + off);
    }}
  }}

  for (let g = 0; g < {max_pages - init_pages}; g++) {{
    tryRun(() => {{
      let old = instance.exports.grow(1);
      let newAddr = old * pageSize;
      instance.exports.store32(newAddr, 0xCAFE0000 + g);
      instance.exports.load32(newAddr);
      instance.exports.fill(newAddr, 0xAA, Math.min(256, pageSize));
    }}, 'grow_' + g);
  }}

  tryRun(() => {{
    const view = new DataView(instance.exports.mem.buffer);
    for (let i = 0; i < Math.min(view.byteLength, 1024); i += 4) {{
      view.getInt32(i, true);
    }}
  }}, 'js_view');
}})();
"""


GENERATORS = {
    "table_lazy": gen_table_lazy,
    "table_cross_instance": gen_table_cross_instance,
    "funcref_resolution": gen_funcref_resolution,
    "gc_struct_cast": gen_gc_struct_cast,
    "gc_array_bounds": gen_gc_array_bounds,
    "multi_table_dispatch": gen_multi_table_dispatch,
    "table_grow_funcref": gen_table_grow_funcref,
    "gc_subtype_hierarchy": gen_gc_subtype_hierarchy,
    "import_reexport_chain": gen_import_reexport_chain,
    "memory_boundary": gen_memory_boundary,
}


def main():
    parser = argparse.ArgumentParser(description="WasmGC sandbox-boundary corpus generator")
    parser.add_argument("--out-dir", required=True, help="Output directory for generated JS files")
    parser.add_argument("--count", type=int, default=100, help="Number of test cases to generate")
    parser.add_argument("--surface", choices=SURFACES, help="Generate only this surface (default: all)")
    parser.add_argument("--seed", type=int, default=None, help="Base seed (default: random)")
    args = parser.parse_args()

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    base_seed = args.seed if args.seed is not None else random.randint(0, 2**31)
    surfaces = [args.surface] if args.surface else SURFACES
    generated = 0

    for i in range(args.count):
        seed = base_seed + i
        surface = surfaces[i % len(surfaces)]
        gen_fn = GENERATORS[surface]

        code = gen_fn(seed)
        filename = f"sbx_{surface}_{seed}.js"
        (out_dir / filename).write_text(code)
        generated += 1

    print(f"Generated {generated} test cases in {out_dir}/ (base_seed={base_seed})")
    print(f"Surfaces: {', '.join(surfaces)}")
    print(f"Run: d8 --sandbox-fuzzing {out_dir}/sbx_*.js")


if __name__ == "__main__":
    main()
